class Sounds{

    static sounds =[
        "car_pass",
        "bell",
        "click",
        "crash",
        "fuel_beep",
        "game_over",
        "get_shield",
        "go",
        "light_1",
        "light_2",
        "lose",
        "shield_hit",
        "start_your_engines",
        "coin",
        "hit",
        "jump",
        "tire",
        "turbo",
        "fail",
        "pause",
        "vanish",
        "bubbles",
        "horn",
        "beach_music_1_80_synth",
        "beach_music_2_summer_hit",
        "beach_music_3_reggae",
        "beach_music_4_bossa_nova",
        "city_music_1_electropop",
        "city_music_2_electro_house",
        "city_music_3_aggressive_electronic",
        "city_music_4_tuning_instrumental",
        "farm_music_1_terra_incognita",
        "farm_music_2_green_fields",
        "farm_music_3_8_bit",
        "farm_music_4_bass_and_choir",
        "forest_music_1_happy",
        "forest_music_2_fairy_tale",
        "forest_music_3_digital_garden",
        "forest_music_4_punk_8_bit",
        "suburb_music_1_man_with_long_hair",
        "suburb_music_2_psychedelic_trip",
        "suburb_music_3_disco_funk",
        "suburb_music_4_groovy_electronic",
        "beach_dog_sound",
        "bull_sound",
        "capivara_sound",
        "cat_sound",
        "city_dog_sound",
        "guara_sound",
        "horse_sound",
        "jaguar_sound",
        "suburb_dog_sound",
        "turtle_sound"]

    static contextSounds = {
    }

}
